# Generated by Django 5.2.8 on 2025-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_admintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenreport',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='reports/audio/'),
        ),
        migrations.AlterField(
            model_name='citizenreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/images/'),
        ),
    ]
