# Generated by Django 5.2.8 on 2025-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_citizenreport_audio_alter_citizenreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/admin/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/citizen/'),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'otp_code'], name='api_otp_email_ed0686_idx')],
            },
        ),
    ]
