# Generated by Django 5.2.8 on 2025-11-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_responseteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenreport',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.responseteam'),
        ),
    ]
